# syntax=docker/dockerfile:1

#
# This adds customizations on top of the mediawiki image
#

FROM mediawiki:stable

# Taken from mediawiki Dockerfile
# https://github.com/wikimedia/mediawiki-docker/blob/aa07f326d2719366125551213a2a9be8801aa773/1.39/apache/Dockerfile
CMD ["apache2-foreground"]
